import matter from "gray-matter";

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  author: string;
  excerpt: string;
  tags: string[];
  content: string;
  readingTime: number;
  // Optional fields for future Medium integration
  source?: "local" | "medium" | "external";
  sourceUrl?: string;
  imageUrl?: string; // Optional hero image, but cards remain text-focused
}

// Import generated blog posts (auto-generated from markdown files)
// This file is generated by running: node scripts/generate-blog-imports.js
import { markdownPosts } from './blog-imports.generated';

// The generated posts already have all the data parsed from frontmatter
// Content is imported as raw strings via ?raw
const markdownModules: BlogPost[] = markdownPosts.map(post => ({
  slug: post.slug,
  title: post.title,
  date: post.date,
  author: post.author,
  excerpt: post.excerpt,
  tags: post.tags,
  content: typeof post.content === 'string' ? post.content : String(post.content),
  readingTime: post.readingTime
}));

console.log('=== Blog Loading Debug ===');
console.log('Markdown posts loaded:', markdownModules.length);

// Fallback posts (can be removed once you have markdown files)
const fallbackPosts: BlogPost[] = [
  {
    slug: "introducing-knowledge-stack",
    title: "Introducing Knowledge Stack: The Future of Enterprise Knowledge Management",
    date: "2025-01-15",
    author: "Knowledge Stack Team",
    excerpt: "We're excited to announce Knowledge Stack, a new platform designed to help organizations harness their collective knowledge with AI-powered accuracy and enterprise-grade security.",
    tags: ["Product", "Announcement", "AI"],
    content: `# Introducing Knowledge Stack

We're thrilled to announce the launch of Knowledge Stack, a revolutionary platform designed to transform how organizations manage and access their collective knowledge.

## The Problem

In today's fast-paced business environment, organizations generate vast amounts of information every day. From internal documentation to customer communications, this knowledge is often scattered across multiple systems, making it difficult to find and utilize effectively.

## Our Solution

Knowledge Stack combines cutting-edge AI technology with enterprise-grade security to provide:

- **Complete Source Traceability**: Every answer includes full citations
- **Mission-Critical Accuracy**: Advanced models trained for knowledge work
- **Enterprise Security**: SOC 2 compliant with end-to-end encryption

## What's Next

We're just getting started. Stay tuned for more updates as we continue to build features that help organizations unlock their knowledge potential.`,
    readingTime: 3
  },
  {
    slug: "enterprise-security-best-practices",
    title: "Enterprise Security Best Practices for AI Knowledge Platforms",
    date: "2025-01-10",
    author: "Security Team",
    excerpt: "Learn about the security measures and best practices that ensure your organization's knowledge remains protected when using AI-powered platforms.",
    tags: ["Security", "Enterprise", "Best Practices"],
    content: `# Enterprise Security Best Practices

Security is paramount when dealing with enterprise knowledge. Here are the key practices we follow:

## Data Encryption

All data is encrypted both in transit and at rest using industry-standard encryption protocols.

## Access Control

Role-based access control ensures that only authorized personnel can access sensitive information.

## Compliance

We maintain SOC 2 Type II certification and comply with GDPR, HIPAA, and other regulatory requirements.

## Audit Logging

Comprehensive audit logs track all access and modifications to ensure complete traceability.`,
    readingTime: 5
  },
  {
    slug: "ai-accuracy-in-knowledge-management",
    title: "Achieving AI Accuracy in Knowledge Management",
    date: "2025-01-05",
    author: "AI Research Team",
    excerpt: "How we've built AI models specifically for knowledge work, ensuring reliable and accurate responses that organizations can trust.",
    tags: ["AI", "Technology", "Research"],
    content: `# Achieving AI Accuracy in Knowledge Management

Building AI systems for enterprise knowledge management requires a different approach than general-purpose chatbots.

## The Challenge

Generic AI models often hallucinate or provide inaccurate information, which is unacceptable in enterprise contexts where decisions depend on reliable data.

## Our Approach

We've trained specialized models on enterprise knowledge tasks, with a focus on:

1. **Retrieval-Augmented Generation**: Always grounding answers in source documents
2. **Confidence Scoring**: Providing confidence levels for each answer
3. **Source Citations**: Full traceability back to original documents

## Results

Our models achieve 95%+ accuracy on enterprise knowledge tasks, significantly higher than general-purpose models.`,
    readingTime: 7
  }
];

// Get all posts from generated imports, fallback to hardcoded posts if none found
const blogPosts: BlogPost[] = markdownModules.length > 0 ? markdownModules : fallbackPosts;
console.log('Total blog posts:', blogPosts.length);

export function getAllPosts(): BlogPost[] {
  return blogPosts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}

export function getPostsByTag(tag: string): BlogPost[] {
  return blogPosts.filter((post) => post.tags.includes(tag));
}

export function getAllTags(): string[] {
  const tags = new Set<string>();
  blogPosts.forEach((post) => {
    post.tags.forEach((tag) => tags.add(tag));
  });
  return Array.from(tags).sort();
}

// Calculate reading time (approximate: 200 words per minute)
export function calculateReadingTime(content: string): number {
  const words = content.split(/\s+/).length;
  return Math.ceil(words / 200);
}

